# Generated by Django 5.0.4 on 2024-05-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='user',
        ),
    ]
