# Generated by Django 5.0.4 on 2024-05-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0002_remove_demande_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132)),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=132)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.CharField(max_length=132)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.RemoveField(
            model_name='demande',
            name='achat',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='quantite',
        ),
        migrations.AddField(
            model_name='demande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=135)),
                ('quantite', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('type_compte', models.CharField(choices=[('ADB', 'Achats de biens'), ('ASC', 'Achats de services et charges permanentes')], default='ADB', max_length=3)),
                ('type_achat', models.CharField(choices=[('BR', 'Burreau'), ('OR', 'Ordinateur'), ('IN', 'Internet'), ('SR', 'Service')], default='BR', max_length=2)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.demande')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AlterField(
            model_name='employer',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fact_app.departement'),
        ),
    ]
