# Generated by Django 5.0.4 on 2024-05-11 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0005_article_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='fournisseur',
        ),
        migrations.AddField(
            model_name='demande',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.fournisseur'),
            preserve_default=False,
        ),
    ]
