# Generated by Django 5.0.4 on 2024-05-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0007_remove_demande_article_demande_article_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='article_name',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='article_quantite',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='article_unit_price',
        ),
        migrations.AlterField(
            model_name='demande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=135)),
                ('quantity', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.demande')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
