# Generated by Django 5.0.4 on 2024-05-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0008_remove_demande_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10000, null=True),
        ),
    ]
