# Generated by Django 5.0.4 on 2024-05-17 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0009_alter_demande_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='demande',
        ),
        migrations.AddField(
            model_name='article',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.article'),
            preserve_default=False,
        ),
    ]
