# Generated by Django 5.0.6 on 2024-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0010_remove_article_demande_article_employer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='article',
        ),
        migrations.AddField(
            model_name='demande',
            name='articles',
            field=models.ManyToManyField(related_name='demandes', to='fact_app.article'),
        ),
    ]
