# Generated by Django 5.0.6 on 2024-06-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0011_remove_demande_article_demande_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='articles',
        ),
        migrations.AddField(
            model_name='demande',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.article'),
            preserve_default=False,
        ),
    ]
