# Generated by Django 5.0.6 on 2024-06-01 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0013_remove_demande_article_alter_article_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.employer'),
        ),
    ]
