# Generated by Django 5.0.6 on 2024-06-02 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0015_remove_demande_article_demande_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='articles',
        ),
        migrations.AddField(
            model_name='demande',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compte',
            name='type_achat',
            field=models.CharField(choices=[('BR', 'Burreau'), ('OR', 'Ordinateur'), ('IN', 'Internet'), ('SR', 'Service')], max_length=2),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_achat',
            field=models.CharField(choices=[('BR', 'Burreau'), ('OR', 'Ordinateur'), ('IN', 'Internet'), ('SR', 'Service')], default='BR', max_length=2),
        ),
    ]
