# Generated by Django 5.0.6 on 2024-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0016_remove_demande_articles_demande_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=100000000000000, null=True),
        ),
    ]
