# Generated by Django 5.0.6 on 2024-06-03 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0017_alter_demande_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='demande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fact_app.demande'),
            preserve_default=False,
        ),
    ]
